// Mocks generated by Mockito 5.4.5 from annotations
// in kanban_board/test/feature/task/data/repository/timer_repository_impl/timer_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanban_board/feature/task/data/datasource/timer_local_datasource.dart'
    as _i2;
import 'package:kanban_board/feature/task/data/models/task_timer_model/task_timer_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TimerLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerLocalDatasource extends _i1.Mock
    implements _i2.TimerLocalDatasource {
  MockTimerLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskTimerModel? getTimer(String? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #getTimer,
        [taskId],
      )) as _i3.TaskTimerModel?);

  @override
  _i4.Future<void> saveTimer(_i3.TaskTimerModel? timer) => (super.noSuchMethod(
        Invocation.method(
          #saveTimer,
          [timer],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTimer(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTimer,
          [taskId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i3.TaskTimerModel?> getAllTimers() => (super.noSuchMethod(
        Invocation.method(
          #getAllTimers,
          [],
        ),
        returnValue: <_i3.TaskTimerModel?>[],
      ) as List<_i3.TaskTimerModel?>);
}
