// Mocks generated by Mockito 5.4.5 from annotations
// in kanban_board/test/feature/task/data/repository/task_repository_impl/task_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanban_board/feature/task/data/datasource/task_remote_datasource.dart'
    as _i3;
import 'package:kanban_board/feature/task/data/models/task_model/task_model.dart'
    as _i2;
import 'package:kanban_board/feature/task/domain/params/upsert_task_params.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRemoteDataSource extends _i1.Mock
    implements _i3.TaskRemoteDataSource {
  MockTaskRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getTasks() => (super.noSuchMethod(
        Invocation.method(
          #getTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i2.TaskModel>>.value(<_i2.TaskModel>[]),
      ) as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel> createTask(
          {required _i5.UpsertTaskParams? upsertTaskParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [],
          {#upsertTaskParams: upsertTaskParams},
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #createTask,
            [],
            {#upsertTaskParams: upsertTaskParams},
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> updateTask(
          {required _i5.UpsertTaskParams? upsertTaskParams}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [],
          {#upsertTaskParams: upsertTaskParams},
        ),
        returnValue: _i4.Future<_i2.TaskModel>.value(_FakeTaskModel_0(
          this,
          Invocation.method(
            #updateTask,
            [],
            {#upsertTaskParams: upsertTaskParams},
          ),
        )),
      ) as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<void> completeTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
