// Mocks generated by Mockito 5.4.5 from annotations
// in kanban_board/test/feature/task/domain/usecases/tasks_usecase/get_task_status_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:kanban_board/core/error/failures.dart' as _i6;
import 'package:kanban_board/feature/task/domain/entities/task.dart' as _i7;
import 'package:kanban_board/feature/task/domain/entities/task_timer.dart'
    as _i4;
import 'package:kanban_board/feature/task/domain/repositories/timer_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerRepository extends _i1.Mock implements _i3.TimerRepository {
  MockTimerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TaskTimerEntity? getTimer(String? taskId) =>
      (super.noSuchMethod(Invocation.method(
        #getTimer,
        [taskId],
      )) as _i4.TaskTimerEntity?);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> startTimer(
          _i7.TaskEntity? taskEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTimer,
          [taskEntity],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #startTimer,
            [taskEntity],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> stopTimer(
          _i4.TaskTimerEntity? timer) =>
      (super.noSuchMethod(
        Invocation.method(
          #stopTimer,
          [timer],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #stopTimer,
            [timer],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> pauseTimer(
          _i4.TaskTimerEntity? timer) =>
      (super.noSuchMethod(
        Invocation.method(
          #pauseTimer,
          [timer],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #pauseTimer,
            [timer],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> resumeTimer(
          _i4.TaskTimerEntity? timer) =>
      (super.noSuchMethod(
        Invocation.method(
          #resumeTimer,
          [timer],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #resumeTimer,
            [timer],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> clearTimer(String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTimer,
          [taskId],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #clearTimer,
            [taskId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i2.Either<_i6.Failure, List<_i4.TaskTimerEntity>> getAllCompletedTimers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCompletedTimers,
          [],
        ),
        returnValue: _FakeEither_0<_i6.Failure, List<_i4.TaskTimerEntity>>(
          this,
          Invocation.method(
            #getAllCompletedTimers,
            [],
          ),
        ),
      ) as _i2.Either<_i6.Failure, List<_i4.TaskTimerEntity>>);
}
